export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//Appoinmtents types
export const APPOINTMENTS_LOADED = 'APPOINTMENTS_LOADED';
export const CAR_LOADED = 'CAR_LOADED';
export const LOCATION_SET = 'LOCATION_SET';
export const LOADING= 'LOADING';
export const NOT_LOADING= 'NOT_LOADING';
export const APPOINTMENTS_GARAGES_LOADED= 'APPOINTMENTS_GARAGES_LOADED';



